### PR TITLE
Sort foods

### PR DESCRIPTION
**Pull request by JesusGonzalezA**
The goal is to accomplish the requirements:
- **extension method usage requirement**
- **implementation of a .Net interface**

- I used the cloneable interface to make a deep copy of the array.
- I used the IComparer interface to sort by different ways. If we use IComparable in food we can only sort by x, by this way we can add methods to the IEnumerable<Food> type and we can sort by whatever you want.

Closes #65 

Captura de pantalla 2021-10-01 a las 12 00 16

### CODE REVIEW

**Comment by DonatasPuc** [comment]
Are you sure that you have commited everything? Because I can't see any functions named 'SortByNew' and 'SortByPrice' when I tried to replicate your example.

**Comment by JesusGonzalezA** [comment]
> Are you sure that you have commited everything? Because I can't see any functions named 'SortByNew' and 'SortByPrice' when I tried to replicate your example.

Yeah, that's true. How can I add a new commit to this existing pr?

**Comment by DonatasPuc** [comment]
> Yeah, that's true. How can I add a new commit to this existing pr?

Just push your commits to this branch. It will update automatically.

**Comment by JesusGonzalezA** [comment]
> > Yeah, that's true. How can I add a new commit to this existing pr?
> 
> Just push your commits to this branch. It will update automatically.

I beleive that you should be able to replicate my example now

**Comment by DonatasPuc** [comment]
Why do you need to clone the list in the extension methods?

**Comment by JesusGonzalezA** [comment]
> Why do you need to clone the list in the extension methods?

I wanted the sort method to return a new sorted list, so I needed to clone it. Thinking about it twice, the original sort method does not have that behaviour so I can sort the list instead of returning another one. Maybe I should delete this pr and change it, what do you think?

**Comment by DonatasPuc** [comment]
I think that it's a good example of using extension methods, but I don't think that cloning a list is necessary. 

Maybe in the future we can refactor this to be more easily extendable. For example, by passing an enum parameter by which to sort the list.

**Review by DonatasPuc — CHANGES_REQUESTED** [review]
Remove cloning from extension methods.

**Comment by JesusGonzalezA** [comment]
> > Why do you need to clone the list in the extension methods?
> 
> I wanted the sort method to return a new sorted list, so I needed to clone it. Thinking about it twice, the original sort method does not have that behaviour so I can sort the list instead of returning another one. Maybe I should delete this pr and change it, what do you think?

Captura de pantalla 2021-10-01 a las 15 03 10

I have been searching on the web and I cannot implement it the way I wanted (sorting the list passed as an argument instead of returning a new one). it seems that the use of ref in extension methods is not allowed for classes, so I'd be sorting a value instead of the actual list, and it won't work. https://stackoverflow.com/questions/2618597/impossible-to-use-ref-and-out-for-first-this-parameter-in-extension-methods

**Pull request closed without merging**
